x-volume-common:
  &volume-common
  driver: local
  driver_opts:
    &volume-driver-opts-common
    type: none
    o: bind

services:
  minio:
    image: ${MINIO_IMAGE_NAME:-bitnami/minio:2024}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-null}
    volumes:
      - minio-volume:/bitnami/minio/data
    healthcheck:
      test: ["CMD", "mc", "-ready", "local"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 20s
    restart: on-failure:3
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"

  spark-master:
    image: ${SPARK_IMAGE_NAME:-bitnami/spark:3.5.4}
    environment:
      SPARK_MODE: master
    depends_on:
      - minio
    restart: on-failure:3
    ports:
      - "${SPARK_API_PORT:-7077}:7077"
      - "${SPARK_CONSOLE_PORT:-8080}:8080"
      - "${SPARK_WEB_UI_PORT:-8081}:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spark-worker:
    image: ${SPARK_IMAGE_NAME:-bitnami/spark:3.5.4}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    depends_on:
      - spark-master
      - minio
    restart: on-failure:3
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  minio-volume:
    <<: *volume-common
    driver_opts:
      <<: *volume-driver-opts-common
      device: ${PROJ_DIR:-.}/minio-data